Allow build on other *nix platforms
Sinono3/souvlaki pull request #26
Opened 2022-06-07 12:13 UTC by 0323pin

Suggestion to address https://github.com/Sinono3/souvlaki/issues/25

It builds standalone on NetBSD.

2022-06-08 00:52 UTC, Sinono3 requested changes
- AFAIK `unix` doesn't exist in `target_os`, so I'm not sure how it compiled.
- I think the `unix` module should be renamed to `mpris`. That way it would be easier to find.
- Cargo.lock should be removed and ignored

2022-06-08 00:52 UTC, Sinono3 commented on .gitignore
> -Cargo.lock
`Cargo.lock` should stay in the gitignore because souvlaki is a library, not a binary

2022-06-08 00:52 UTC, Sinono3 commented on src/platform/mod.rs
> +#[cfg(target_os = "unix")]
You could change all these gates to: `#[cfg(all(unix, not(target_os = "macos")))]`. Because matching with all Unix platforms may conflict with MacOS.

2022-06-08 00:54 UTC, Sinono3 commented
Thanks for the PR! I appreciate it. I've left a few notes on the code.

2022-06-08 10:34 UTC, 0323pin commented
@Sinono3 Ok now, or did I miss something? Sorry, I'm not a programmer, just a package maintainer trying my best 😄 
According to https://doc.rust-lang.org/reference/conditional-compilation.html looks to be possible to use `target_family = "unix"`

If not maybe use a list `cfg(target_os = "linux", target_os = "netbsd")` adding the other unixs defined in the reference above.

2022-06-16 00:46 UTC, Sinono3 commented
> If not maybe use a list cfg(target_os = "linux", target_os = "netbsd") adding the other unixs defined in the reference above.

That's probably the safest bet. Can you change that?

2022-06-16 07:31 UTC, 0323pin commented
@Sinono3 Sure, no problem. I've checked that those platforms do have `dbus` support. I don't use any of them, though.

Or, did you mean to convert all feature gates to the same syntax as well?

2022-06-16 20:20 UTC, 0323pin commented
@Sinono3 Suck! I'm sorry that the last commit kicked an extra CI build that was doomed to fail due to yet another typo. I should be more careful :(

2022-06-19 12:11 UTC, 0323pin commented
@Sinono3 give the CI another go, I've fixed the typo.

2022-07-09 04:53 UTC, 0323pin commented
@Sinono3 😞 Any hints on something obvious that I'm failing to see?

2022-07-09 07:33 UTC, 0323pin commented
@Sinono3 Ok, I'm sorry, I should have done this myself before requesting a CI build.
It build now for me,

```
souvlaki > cargo build --release
   Compiling pkg-config v0.3.25
   Compiling libc v0.2.126
   Compiling souvlaki v0.5.1 (/home/pin/Downloads/souvlaki)
   Compiling libdbus-sys v0.2.2
   Compiling dbus v0.9.5
   Compiling dbus-crossroads v0.5.0
    Finished release [optimized] target(s) in 48.75s
```

2022-07-18 22:15 UTC, merged

2022-07-19 06:58 UTC, 0323pin commented
@Sinono3 Thank you 👍